### ISSUE TITLE
Cannot invoke initializer for type 'UInt' with an argument list of type '(objc_AssociationPolicy)'

### ISSUE THREAD

**Issue by sekouperry** [Yalantis/Side-Menu.iOS#19] opened 2015-09-18 20:08 UTC
In MenuSegue.swift
![screen shot 2015-09-18 at 4 07 13 pm](https://cloud.githubusercontent.com/assets/3640832/9969883/5fe1f8ac-5e1f-11e5-89d2-22c0bd3b108b.png)

objc_setAssociatedObject(presented, &key, self, UInt(objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC))
        return MenuTransitionAnimator(.Presentation)
    }

**Comment by advantis** [comment] 2015-09-28 12:44
Duplicate of #20

**Closed by advantis** 2015-09-28 12:44 UTC
